### ISSUE TITLE
I can't change the color or close the app

### ISSUE THREAD

**Issue by DarkoSvitic** [romannurik/MaterialColorsApp#1]
Also when I run gulp I get this error. 

![default](https://cloud.githubusercontent.com/assets/4858536/14014885/b55f0390-f1b5-11e5-84b1-721bbfcfb44d.jpg)

**Comment by romannurik** [comment]
Haven't really tested on Windows :-/

**Comment by DarkoSvitic** [comment]
I will try at home, maybe it's just something wrong with office pc's :P

**Comment by filippofavaro** [comment]
@DarkoSvitic unfortunately I've the same problem, I think that it's a bug related only to Windows

**Comment by DarkoSvitic** [comment]
@filippofavaro I think it's related to electron-osx-sign

**Comment by ziggy42** [comment]
Same problem on Linux (Ubuntu 16.04)
