### ISSUE TITLE
Search for color

### ISSUE THREAD

**Issue by brunowego** [romannurik/MaterialColorsApp#10]
Think add a option for hexadecimal search :+1:

**Comment by romannurik** [comment]
Do you mean, given a hex value, show which material color it is, if it's a material color?

**Comment by brunowego** [comment]
Yes @romannurik

**Comment by jackmu95** [comment]
Is that really that useful? @brunowego
Wouldn't it make much more sense when the search could handle a color name search like "blue" and would respond with all blueish colors.

**Comment by brunowego** [comment]
I believe I am not knowing explain it. I have some projects that used the colors of the design material, however need to know what the color name, unfortunately the developers did not put it in the code.

**Comment by mvoshell** [comment]
Yea so if you could call it through the mac os spotlight search would be cool too :)

**Comment by romannurik** [comment]
A colleague at Google is taking a stab at this.

**Comment by romannurik** [comment]
Basic support added in master. Closing for now.
