### ISSUE TITLE
Windows Support?

### ISSUE THREAD

**Issue by filfat** [romannurik/MaterialColorsApp#11]
Having support for Windows would be awesome, perhaps it could be placed in the notification tray?

**Comment by romannurik** [comment]
I'd love to link to a Windows fork but don't plan on supporting an official build for Windows. FWIW, building from source should theoretically work on Windows but I haven't tried it myself.

**Comment by e-krebs** [comment]
A few things don't work on windows (at least windows 10):
- background is black (body { background-color: white; } fix it
- hues : clicking on them doesn't do a thing (plus no cursor: pointer;)
- close icon doesn't work (plus no cursor: pointer; either)

**Comment by romannurik** [comment]
No current plans for an official Windows version but would love to link to a Windows fork
