### ISSUE TITLE
Move the Close Button to the Left?

### ISSUE THREAD

**Issue by preshit** [romannurik/MaterialColorsApp#13]
I've pulling my hair out every time I try to dismiss the window. Because Mac apps use the close button on the left, I keep hitting RED circle every time. The close button on the right really bothers me. 

Can you move it to the left like other apps? 

The close button is also aligned 1px to the left compared to the other cells.

![Alignement Issue Screenshot](https://cloud.githubusercontent.com/assets/703568/14215618/b22e5498-f861-11e5-87bd-eb375aea33f4.png)

**Comment by romannurik** [comment]
this would be part of a larger redesign at some point; the current placement is intentional although clearly not ideal
