### ISSUE TITLE
Add app menu in normal mode allowing to switch back to menu bar mode

### ISSUE THREAD

**Issue by Zoramite** [romannurik/MaterialColorsApp#17]
I was playing with the mode shown in the menu bar icon and there was the option to remove it or switch to a mode that turns off the icon, and now I can't figure out how to get it to go back to the mode that has the menu bar icon... 😿 

Am I missing something or can you add a way to turn the menu bar icon back on?

**Comment by romannurik** [comment]
Currently the only way to switch back is to right click on the Dock icon and press Switch to Normal App Mode. I'm planning to make this more obvious w/ an app menu bar.
