### ISSUE TITLE
Context menu mode

### ISSUE THREAD

**Issue by acondiff** [romannurik/MaterialColorsApp#2]
I'd really find it useful if this app was more of a quick reference where you would click on the menubar icon, select your color, and instead of clicking the X to close, you could simply click away and it would close similar to other menubar apps. In this mode it might be nice to have a arrow pointing up to the menubar icon and not have it be draggable. It would also not display the X.

![image](https://cloud.githubusercontent.com/assets/806104/14022774/523b42e8-f1af-11e5-9953-bdee89cad1cf.png)

**Comment by romannurik** [comment]
Excellent idea; see my comment in #6; I think it's best this live as a fork for now; we can explore adding it as another mode in the future.

**Comment by DarrylBayliss** [comment]
@romannurik Would you prefer #6 as an optional mode that doesn't remove the current navigation?

**Comment by romannurik** [comment]
That might be a useful option :)

**Comment by romannurik** [comment]
After 2 years, I'm finally adding this option :)

**Comment by romannurik** [comment]
Added this as an option in a472ee98d9c0d0c7929625743578b310d8a55efc
