### ISSUE TITLE
Sketch color picker wrong 

### ISSUE THREAD

**Issue by sseanhurleyy** [romannurik/MaterialColorsApp#26]
![image](https://cloud.githubusercontent.com/assets/21298602/19175835/12381406-8c86-11e6-9891-cb2fcfba007e.png)

When I use the color picker in Sketch, the color in the MaterialColoursApp registers as a different color to the HEX value listed. 

Would be verrrryyy convenient if this weren't the case. 

Cheers, 

Sean

**Comment by romannurik** [comment]
Hm I haven't seen this myself. Which version of OSX and Sketch are you using? Do you have any weird color profile setup on your machine or anything else that may be related? Of you have multiple monitors does this happen on all of them?

**Comment by sseanhurleyy** [comment]
Sierra, Sketch 40.1 and using a rMBP with a Thunderbolt Display and no fancy color profile.

**Comment by romannurik** [comment]
Hm, maybe it's Sierra… I'm on El Capitan and correctly get #F44336 when Ctrl+C'ing from Sketch on Red 500 :-/

**Comment by romannurik** [comment]
FWIW, am now able to repro on Sierra. My guess is color profiles in either Sketch or Sierra aren't being handled right. Not sure if there's really a solution to this for the current app.

**Comment by romannurik** [comment]
I *think* this is now better in the latest versions of Sketch..
